# Generated by Django 6.0.4 on 2026-04-24 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StipendEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('is_eligible', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stipend_eligibility', to='students.student')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stipend_validations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StipendApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Validated', 'Validated'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_account', models.CharField(blank=True, max_length=80)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stipend_applications', to='schools.academicyear')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stipend_reviews', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stipend_applications', to='students.student')),
                ('eligibility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='stipend.stipendeligibility')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
