# Generated by Django 6.0.4 on 2026-04-23 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_seed_letters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='audio_first_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='high_contrast_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='inclusive_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='large_text_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='simplified_layout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exerciseattempt',
            name='exercise_type',
            field=models.CharField(default='standard', max_length=30),
        ),
        migrations.AddField(
            model_name='letterprogress',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='letterprogress',
            name='incorrect_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AdultProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adult_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('english', 'English'), ('bangla', 'Bangla')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='learning.childprofile')),
                ('letters', models.ManyToManyField(blank=True, related_name='lesson_assignments', to='learning.letter')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='learning.adultprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
