# Generated by Django 6.0.4 on 2026-04-24 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_on', models.DateField()),
                ('visited_on', models.DateField(blank=True, null=True)),
                ('focus_area', models.CharField(max_length=160)),
                ('findings', models.TextField(blank=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Follow-up Required', 'Follow-up Required')], default='Scheduled', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='schools.school')),
                ('ueo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_on'],
            },
        ),
        migrations.CreateModel(
            name='InspectionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('file', models.FileField(upload_to='inspection_evidence/')),
                ('note', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='inspections.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('action_plan', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=30)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='inspections.inspection')),
            ],
            options={
                'ordering': ['status', 'due_date'],
            },
        ),
    ]
