LETTER_CATALOG = [
    {"language": "english", "symbol": "A", "name": "A", "transliteration": "Ay", "word": "Apple", "word_translation": "A juicy red fruit", "emoji": "🍎", "description": "A is for Apple.", "speech_text": "A for Apple", "sort_order": 1},
    {"language": "english", "symbol": "B", "name": "B", "transliteration": "Bee", "word": "Ball", "word_translation": "A round toy", "emoji": "⚽", "description": "B is for Ball.", "speech_text": "B for Ball", "sort_order": 2},
    {"language": "english", "symbol": "C", "name": "C", "transliteration": "See", "word": "Cat", "word_translation": "A playful cat", "emoji": "🐱", "description": "C is for Cat.", "speech_text": "C for Cat", "sort_order": 3},
    {"language": "english", "symbol": "D", "name": "D", "transliteration": "Dee", "word": "Dog", "word_translation": "A friendly dog", "emoji": "🐶", "description": "D is for Dog.", "speech_text": "D for Dog", "sort_order": 4},
    {"language": "english", "symbol": "E", "name": "E", "transliteration": "Ee", "word": "Egg", "word_translation": "A breakfast egg", "emoji": "🥚", "description": "E is for Egg.", "speech_text": "E for Egg", "sort_order": 5},
    {"language": "english", "symbol": "F", "name": "F", "transliteration": "Ef", "word": "Fish", "word_translation": "A swimming fish", "emoji": "🐟", "description": "F is for Fish.", "speech_text": "F for Fish", "sort_order": 6},
    {"language": "english", "symbol": "G", "name": "G", "transliteration": "Jee", "word": "Goat", "word_translation": "A little goat", "emoji": "🐐", "description": "G is for Goat.", "speech_text": "G for Goat", "sort_order": 7},
    {"language": "english", "symbol": "H", "name": "H", "transliteration": "Aych", "word": "Hat", "word_translation": "A sunny hat", "emoji": "👒", "description": "H is for Hat.", "speech_text": "H for Hat", "sort_order": 8},
    {"language": "english", "symbol": "I", "name": "I", "transliteration": "Eye", "word": "Ice Cream", "word_translation": "A sweet dessert", "emoji": "🍦", "description": "I is for Ice Cream.", "speech_text": "I for Ice Cream", "sort_order": 9},
    {"language": "english", "symbol": "J", "name": "J", "transliteration": "Jay", "word": "Juice", "word_translation": "Fresh fruit juice", "emoji": "🧃", "description": "J is for Juice.", "speech_text": "J for Juice", "sort_order": 10},
    {"language": "english", "symbol": "K", "name": "K", "transliteration": "Kay", "word": "Kite", "word_translation": "A kite in the sky", "emoji": "🪁", "description": "K is for Kite.", "speech_text": "K for Kite", "sort_order": 11},
    {"language": "english", "symbol": "L", "name": "L", "transliteration": "El", "word": "Lion", "word_translation": "A brave lion", "emoji": "🦁", "description": "L is for Lion.", "speech_text": "L for Lion", "sort_order": 12},
    {"language": "english", "symbol": "M", "name": "M", "transliteration": "Em", "word": "Moon", "word_translation": "The bright moon", "emoji": "🌙", "description": "M is for Moon.", "speech_text": "M for Moon", "sort_order": 13},
    {"language": "english", "symbol": "N", "name": "N", "transliteration": "En", "word": "Nest", "word_translation": "A bird nest", "emoji": "🪺", "description": "N is for Nest.", "speech_text": "N for Nest", "sort_order": 14},
    {"language": "english", "symbol": "O", "name": "O", "transliteration": "Oh", "word": "Orange", "word_translation": "A juicy orange", "emoji": "🍊", "description": "O is for Orange.", "speech_text": "O for Orange", "sort_order": 15},
    {"language": "english", "symbol": "P", "name": "P", "transliteration": "Pee", "word": "Parrot", "word_translation": "A talking bird", "emoji": "🦜", "description": "P is for Parrot.", "speech_text": "P for Parrot", "sort_order": 16},
    {"language": "english", "symbol": "Q", "name": "Q", "transliteration": "Cue", "word": "Queen", "word_translation": "A royal queen", "emoji": "👑", "description": "Q is for Queen.", "speech_text": "Q for Queen", "sort_order": 17},
    {"language": "english", "symbol": "R", "name": "R", "transliteration": "Ar", "word": "Rainbow", "word_translation": "Colors in the sky", "emoji": "🌈", "description": "R is for Rainbow.", "speech_text": "R for Rainbow", "sort_order": 18},
    {"language": "english", "symbol": "S", "name": "S", "transliteration": "Es", "word": "Sun", "word_translation": "The shining sun", "emoji": "☀️", "description": "S is for Sun.", "speech_text": "S for Sun", "sort_order": 19},
    {"language": "english", "symbol": "T", "name": "T", "transliteration": "Tee", "word": "Tiger", "word_translation": "A striped tiger", "emoji": "🐯", "description": "T is for Tiger.", "speech_text": "T for Tiger", "sort_order": 20},
    {"language": "english", "symbol": "U", "name": "U", "transliteration": "You", "word": "Umbrella", "word_translation": "An umbrella for rain", "emoji": "☂️", "description": "U is for Umbrella.", "speech_text": "U for Umbrella", "sort_order": 21},
    {"language": "english", "symbol": "V", "name": "V", "transliteration": "Vee", "word": "Van", "word_translation": "A family van", "emoji": "🚐", "description": "V is for Van.", "speech_text": "V for Van", "sort_order": 22},
    {"language": "english", "symbol": "W", "name": "W", "transliteration": "Double U", "word": "Whale", "word_translation": "A giant whale", "emoji": "🐋", "description": "W is for Whale.", "speech_text": "W for Whale", "sort_order": 23},
    {"language": "english", "symbol": "X", "name": "X", "transliteration": "Ex", "word": "Xylophone", "word_translation": "A musical instrument", "emoji": "🎼", "description": "X is for Xylophone.", "speech_text": "X for Xylophone", "sort_order": 24},
    {"language": "english", "symbol": "Y", "name": "Y", "transliteration": "Why", "word": "Yarn", "word_translation": "Soft colorful yarn", "emoji": "🧶", "description": "Y is for Yarn.", "speech_text": "Y for Yarn", "sort_order": 25},
    {"language": "english", "symbol": "Z", "name": "Z", "transliteration": "Zee", "word": "Zebra", "word_translation": "A striped zebra", "emoji": "🦓", "description": "Z is for Zebra.", "speech_text": "Z for Zebra", "sort_order": 26},
    {"language": "bangla", "symbol": "অ", "name": "অ", "transliteration": "Aw", "word": "অজগর", "word_translation": "Python snake", "emoji": "🐍", "description": "অ অজগর আসছে তেড়ে।", "speech_text": "অ, অজগর", "sort_order": 101},
    {"language": "bangla", "symbol": "আ", "name": "আ", "transliteration": "Aa", "word": "আম", "word_translation": "Mango", "emoji": "🥭", "description": "আ for আম.", "speech_text": "আ, আম", "sort_order": 102},
    {"language": "bangla", "symbol": "ই", "name": "ই", "transliteration": "I", "word": "ইঁদুর", "word_translation": "Mouse", "emoji": "🐭", "description": "ই for ইঁদুর.", "speech_text": "ই, ইঁদুর", "sort_order": 103},
    {"language": "bangla", "symbol": "ঈ", "name": "ঈ", "transliteration": "Ii", "word": "ঈগল", "word_translation": "Eagle", "emoji": "🦅", "description": "ঈ for ঈগল.", "speech_text": "ঈ, ঈগল", "sort_order": 104},
    {"language": "bangla", "symbol": "উ", "name": "উ", "transliteration": "U", "word": "উট", "word_translation": "Camel", "emoji": "🐪", "description": "উ for উট.", "speech_text": "উ, উট", "sort_order": 105},
    {"language": "bangla", "symbol": "ঊ", "name": "ঊ", "transliteration": "Uu", "word": "ঊষা", "word_translation": "Dawn", "emoji": "🌅", "description": "ঊ for ঊষা.", "speech_text": "ঊ, ঊষা", "sort_order": 106},
    {"language": "bangla", "symbol": "ঋ", "name": "ঋ", "transliteration": "Ri", "word": "ঋষি", "word_translation": "Sage", "emoji": "🧘", "description": "ঋ for ঋষি.", "speech_text": "ঋ, ঋষি", "sort_order": 107},
    {"language": "bangla", "symbol": "এ", "name": "এ", "transliteration": "E", "word": "একতারা", "word_translation": "A musical instrument", "emoji": "🎸", "description": "এ for একতারা.", "speech_text": "এ, একতারা", "sort_order": 108},
    {"language": "bangla", "symbol": "ঐ", "name": "ঐ", "transliteration": "Oi", "word": "ঐরাবত", "word_translation": "Sacred elephant", "emoji": "🐘", "description": "ঐ for ঐরাবত.", "speech_text": "ঐ, ঐরাবত", "sort_order": 109},
    {"language": "bangla", "symbol": "ও", "name": "ও", "transliteration": "O", "word": "ওল", "word_translation": "Yam", "emoji": "🍠", "description": "ও for ওল.", "speech_text": "ও, ওল", "sort_order": 110},
    {"language": "bangla", "symbol": "ঔ", "name": "ঔ", "transliteration": "Ou", "word": "ঔষধ", "word_translation": "Medicine", "emoji": "💊", "description": "ঔ for ঔষধ.", "speech_text": "ঔ, ঔষধ", "sort_order": 111},
    {"language": "bangla", "symbol": "ক", "name": "ক", "transliteration": "Ko", "word": "কাক", "word_translation": "Crow", "emoji": "🐦", "description": "ক for কাক.", "speech_text": "ক, কাক", "sort_order": 112},
    {"language": "bangla", "symbol": "খ", "name": "খ", "transliteration": "Kho", "word": "খরগোশ", "word_translation": "Rabbit", "emoji": "🐇", "description": "খ for খরগোশ.", "speech_text": "খ, খরগোশ", "sort_order": 113},
    {"language": "bangla", "symbol": "গ", "name": "গ", "transliteration": "Go", "word": "গরু", "word_translation": "Cow", "emoji": "🐄", "description": "গ for গরু.", "speech_text": "গ, গরু", "sort_order": 114},
    {"language": "bangla", "symbol": "ঘ", "name": "ঘ", "transliteration": "Gho", "word": "ঘোড়া", "word_translation": "Horse", "emoji": "🐎", "description": "ঘ for ঘোড়া.", "speech_text": "ঘ, ঘোড়া", "sort_order": 115},
    {"language": "bangla", "symbol": "ঙ", "name": "ঙ", "transliteration": "Ngo", "word": "ঙুরীয়", "word_translation": "Ring-like ornament", "emoji": "💍", "description": "ঙ for ঙুরীয়.", "speech_text": "ঙ, ঙুরীয়", "sort_order": 116},
    {"language": "bangla", "symbol": "চ", "name": "চ", "transliteration": "Cho", "word": "চশমা", "word_translation": "Glasses", "emoji": "👓", "description": "চ for চশমা.", "speech_text": "চ, চশমা", "sort_order": 117},
    {"language": "bangla", "symbol": "ছ", "name": "ছ", "transliteration": "Chho", "word": "ছাতা", "word_translation": "Umbrella", "emoji": "☔", "description": "ছ for ছাতা.", "speech_text": "ছ, ছাতা", "sort_order": 118},
    {"language": "bangla", "symbol": "জ", "name": "জ", "transliteration": "Jo", "word": "জাহাজ", "word_translation": "Ship", "emoji": "🚢", "description": "জ for জাহাজ.", "speech_text": "জ, জাহাজ", "sort_order": 119},
    {"language": "bangla", "symbol": "ঝ", "name": "ঝ", "transliteration": "Jho", "word": "ঝুড়ি", "word_translation": "Basket", "emoji": "🧺", "description": "ঝ for ঝুড়ি.", "speech_text": "ঝ, ঝুড়ি", "sort_order": 120},
    {"language": "bangla", "symbol": "ঞ", "name": "ঞ", "transliteration": "Nyo", "word": "ঞানো", "word_translation": "Learning sound", "emoji": "📚", "description": "ঞ is a special sound letter.", "speech_text": "ঞ", "sort_order": 121},
    {"language": "bangla", "symbol": "ট", "name": "ট", "transliteration": "To", "word": "টমেটো", "word_translation": "Tomato", "emoji": "🍅", "description": "ট for টমেটো.", "speech_text": "ট, টমেটো", "sort_order": 122},
    {"language": "bangla", "symbol": "ঠ", "name": "ঠ", "transliteration": "Tho", "word": "ঠেলা", "word_translation": "Cart", "emoji": "🛒", "description": "ঠ for ঠেলা.", "speech_text": "ঠ, ঠেলা", "sort_order": 123},
]

LANGUAGE_META = {
    "english": {
        "label": "English",
        "hero_title": "Learn English letters with playful sound and color.",
        "voice_hint": "Use your browser audio button to hear pronunciation.",
    },
    "bangla": {
        "label": "Bangla",
        "hero_title": "বাংলা বর্ণ শিখি ছবি, শব্দ আর খেলায়।",
        "voice_hint": "বাটনে চাপ দিয়ে বর্ণের উচ্চারণ শোনো।",
    },
}
